site_name: JTSDK64 Tools User Guide
site_description: SSoftware Development Tools

theme:
    name: 'material'
    features:
      - navigation.tabs

repo_name: JTSDK/jtsdk64-tools
repo_url: https://github.com/JTSDK/jtsdk64-tools
edit_uri: ""
copyright: Documentation Copyright &copy; 2016 - 2021 Greg Beam, KI7MT 

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - attr_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.superfences
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Setup:
    - Overview: 'setup/overview.md'
    - 1. Prerequisites: 'setup/prerequisite.md'
    - 2. Base Install: 'setup/baseinstall.md'
    - 3. Post Install: 'setup/postinstall.md'
    - 4. Build Config: 'setup/buildconfig.md'
    - 5. MSYS2 Setup: 'setup/msys2setup.md'
    - 6. Build Hamlib: 'setup/buildhamlib.md'
    - 7. Deploy Boost: 'setup/deployboost.md'
    - 8. Package WSJT-X: 'setup/packagewsjtx.md'
    - 9. Conslusion: 'setup/conclusion.md'
  - Tools:
    - Overview: 'tools/overview.md'
  - MSYS2:
    - Overview: 'msys2/overview.md'
  - Boost:
    - Overview: 'boost/overview.md'
  - Hamlib:
    - Overview: 'hamlib/overview.md'
  - WSJT-X:
    - Overview: 'wsjtx/overview.md'
  - JS8CALL:
    - Overview: 'js8call/overview.md'
  - JTDX:
    - Overview: 'jtdx/overview.md'
  - Contribute:
    - Overview: 'contribute/overview.md'
  - Credits: credits.md